import "./sass/main.scss"
import "./utils/addHeader.js"
import "./utils/getData.js"
import "./utils/addTemplates.js"
// import "./utils/addAppCart.js"
import "./utils/add_app_cart.js"
import "./utils/loadMoreBtn.js"
import "./utils/auth.js"
import "./utils/search.js"